version: 2.1

jobs:
  hello-job:
    docker:
      - image: centos:7.9.2009 #alpine:latest #cimg/node:17.2.0 # the primary container, where your job's commands are run
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD_ENV #$DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: echo $DOCKER_HUB_USER
      - run: yum install sudo -y
      - run: sudo yum update -y
      - run: sudo yum install -y yum-utils
      - run: sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      #- run: sudo mkdir /sys/fs/cgroup/systemd
      #- run: sudo mount -t cgroup -o none,name=systemd cgroup /sys/fs/cgroup/systemd
      - run: sudo yum install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y
      #- run: sudo yum install httpd -y
      #- run: sudo systemctl start httpd
      - run: sudo systemctl start docker
      - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - run: sudo yum makecache
      - run: sudo yum install unzip -y
      - run: unzip awscliv2.zip
      - run: sudo ./aws/install
      - run: docker image ls #alpine:latest

workflows:
  my-workflow:
    jobs:
      - hello-job #:
          #context:
          #  - DOCKERHUB
          #  - AWS